name: "notify-slack"
description: "notify-slack action"
author: 'Palash Paul'
inputs:
  status:
    description: "The status of the job"
    required: true
    default: "success"
  notify_when:
    description: "When to notify"
    required: true
    default: "always"
  slack_token:
    description: "Slack token"
    required: true
  slack_channel:
    description: "Slack channel"
    required: true
runs:
  using: 'composite'
  steps:
    - name: Run notify-slack
      shell: bash
      run: ${{ github.action_path }}/notify-slack
      env:
        INPUT_STATUS: ${{ inputs.status }}
        INPUT_NOTIFY_WHEN: ${{ inputs.notify_when }}
        INPUT_SLACK_TOKEN: ${{ inputs.slack_token }}
        INPUT_SLACK_CHANNEL: ${{ inputs.slack_channel }}
        GITHUB_API_URL: ${{ github.api_url }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_WORKFLOW: ${{ github.workflow }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_JOB: ${{ github.job }}
