name: Build Binary
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "write"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: "^1.24"

      - name: Install dependencies
        run: |
          make install

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o cmd/cmd cmd/cmd.go
          chmod +x cmd/cmd

      - name: Commit and push binary
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add cmd/cmd
          git commit -m "Update binary [skip ci]" || echo "No changes to commit"
          git push
