name: build
on:
  release:
    types: [published]

concurrency:
  group: build-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
      id-token: "write"
    env:
      LOCATION: europe-west1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: "^1.24"

      - name: Install dependencies
        run: |
          make install

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o cmd/cmd cmd/cmd.go
          chmod +x cmd/cmd

      - name: Commit and push binary
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          # Get the current branch name or tag
          CURRENT_REF="${{ github.ref }}"
          BRANCH_NAME=${CURRENT_REF#refs/tags/}
          # Checkout the master branch
          git checkout master
          # Copy the binary
          cp cmd/cmd cmd/cmd.bak
          git checkout ${{ github.ref }}
          cp cmd/cmd.bak cmd/cmd
          rm cmd/cmd.bak
          # Commit and push
          git add cmd/cmd
          git commit -m "Update binary for release ${{ github.ref_name }}"
          git push origin HEAD:master
